### PR TITLE
Print mock output when building with MockBuilder

### PR DESCRIPTION
**Pull request by vfreex**
Currently when building RPMs or SRPMs with MockBuilder, tito will not print the
output from mock. This makes diagnosis harder especially in CI
environments.

This PR will do the following changes:

1. If `--quiet` option is not specified, `run_command_print` will be used to
run the `mock` or `rpmbuild` command. Otherwise we will continue to use
`run_command`.
2. `run_command_print` will print error message when an error happens, like what `run_command`
does.

### CODE REVIEW

**Comment by vfreex** [comment]
@stevekuznetsov Thanks for your suggestion. Personally I would prefer to see the output during the build procedure, not at the end of build. That's what `run_command_print` does.

**Comment by vfreex** [comment]
@dgoodwin Any suggestions?

**Comment by stevekuznetsov** [comment]
Hadn't thought about needing to do streamed output -- seems reasonable to me but I'll let @dgoodwin weigh in.

**Comment by dgoodwin** [comment]
Yeah I like this, even for default behaiour, when mock is running I'd rather see what it's doing.

Thanks @vfreex

**Pull request merged**
