### PR TITLE
Bugfix: run_command_print should behave similar to run_command

### PR DESCRIPTION
**Pull request by vfreex**
The existing implementation of `run_command_print` uses `shlex.split`
to split command line arguments into an array, but it doesn't handle
wildcards like `run_command`. This breaks Mock build because of failure
of copying generated RPMs.

This PR also adds `print_on_success` argument and unify the behavior of
error handling.

Reproduction:
``` bash
$ tito build --test --rpm --output=artifacts/el6 --builder=tito.builder.MockBuilder --arg=mock=eng-rhel-6-candidate-x86_64
...
INFO: Results and/or logs in: /var/lib/mock/ERROR: Error running command: cp -v /home/fedora/jenkins/workspace/rcm-pulp-rpm-package/artifacts/el6/rpmbuild-pulp-rpm4f6rzL/mockoutput/*.rpm /home/fedora/jenkins/workspace/rcm-pulp-rpm-package/artifacts/el6
```

### CODE REVIEW

**Comment by vfreex** [comment]
@dgoodwin PTAL

**Comment by treydock** [comment]
Ran this patch in production and it resolved my issues.  +1 for getting this released.

**Comment by vfreex** [comment]
@dgoodwin Any updates?

**Comment by Ultimation** [comment]
Also found this PR fixes the same bug I'm encountering, @dgoodwin please consider merging and releasing this change.

**Comment by dgoodwin** [comment]
cc @FrostyX who is taking on some tito responsibilities. I am unfortunately no longer even a tito user so a poor maintainer. :(

**Comment by FrostyX** [comment]
There are some confirmations in the discussion, that this works and fixes the issue, so I am merging.

**Pull request merged**
