### PR TITLE
Modernize Python package

### PR DESCRIPTION
**Pull request by tjanez**
Use setuptool's `console_scripts` entry point mechanism for automatic script creation instead of hard-coded `bin/tito` script (and manually adjusting its she-bang during RPM's `%prep` stage).

Support the popular pip editable installation mode, i.e. `pip install -e .` on a git checkout. Remove the hard-coded `bin/tito-dev` script.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
In order to promote the use of `pip install` or `python setup.py install` we would need to get the dependency list into the `setup.py` or `requirements.txt` ... but that is easier said than done as some of the packages like the RH Bugzilla are not available through `pip`. This makes a full installation through `pip` less than simple, as you would need to grab some dependencies through `pip` and the rest through `dnf`. Before embracing `pip install` perhaps we should figure out a good user experience for that flow.

**Comment by tjanez** [comment]
> In order to promote the use of `pip install` or `python setup.py install` we would need to get the dependency list into the `setup.py` or `requirements.txt` ... but that is easier said than done as some of the packages like the RH Bugzilla are not available through `pip`.

Agreed. At first, I also tried to make `pip install` work without enabling the global site-packages directory but I soon hit the wall... I was able to get `blessings`, `setuptools` and `python-bugzilla` from PyPI but of course no luck with RPM's Python bindings :).

So in the end, I settled for making tito's developer workflow easier and more standard for the casual Python developer. It boiled down to installing tito's dependencies through `dnf` and making it easier to test the *in development* version of tito with `pip install -e .` in its own virtualenv.

If you would like, I could extend these instructions:

```
virtualenv --system-site-packages tito-venv
source tito-venv/bin/activate
pip install -e .
```

with a `dnf` command that installs the dependencies of the current `tito` package in the distribution repository. I think those dependencies should be *good enough* most of the time.

**Comment by stevekuznetsov** [comment]
In my opinion, a solution that would make use of the dependency list in `tito.spec` would be perfect. It feels wrong to hack around it on a project where part of the functionality is to list the dependencies and ensure the install works. @dgoodwin what are your thoughts?

**Comment by tjanez** [comment]
> In my opinion, a solution that would make use of the dependency list in `tito.spec` would be perfect. It feels wrong to hack around it on a project where part of the functionality is to list the dependencies and ensure the install works.

Agreed. I don't know if a `dnf`/`yum` command or a specialized tool for such a thing exists of the top of my head.

Just for the reference, the [installation instructions for installing from source](https://github.com/dgoodwin/tito/blob/master/README.md#install) should also include this command to avoid surprising users.

**Comment by dgoodwin** [comment]
Are we talking about a command to install rpms for the tito.spec deps? If so I think that is recommended if a tito build fails and it looks like a dependency problem:

https://github.com/dgoodwin/tito/blob/master/src/tito/builder/main.py#L1303

**Comment by tjanez** [comment]
> Are we talking about a command to install rpms for the tito.spec deps? If so I think that is recommended if a tito build fails and it looks like a dependency problem:

> https://github.com/dgoodwin/tito/blob/master/src/tito/builder/main.py#L1303

I don't think so. The real issue is how to get the list of tito's dependencies (i.e. packages) from `tito.spec` file.

> In my opinion, a solution that would make use of the dependency list in `tito.spec` would be perfect.

@stevekuznetsov, after thinking about what you said above a bit more, I think that would be very hard to achieve since SPEC file is really a recipe on how to build the package. To get the right list of required packages from the SPEC file one would need to actually built the SRPM on the target platform (keep in mind that RPM also has an automatic requirements generator which includes dependencies beyond what is listed in `Requires:` fields of the SPEC file).

I think a very good, but much simpler solution is to instruct the user to install the packages that are required by the *latest* tito package available for the distribution he is using which can be achieved by this command:
```
sudo dnf install $(dnf repoquery --requires tito --resolve -q)
```

**Caveat** There is a small caveat with the above command. For example, on a Fedora 25 system, the `dnf repoquery --requires tito --resolve -q` command outputs:
```
fedora-cert-0:0.6.0.1-1.fc25.noarch
fedora-packager-0:0.6.0.1-1.fc25.noarch
fedpkg-0:1.26-4.fc25.noarch
perl-4:5.24.1-383.fc25.x86_64
perl-Getopt-Long-0:2.49.1-1.fc25.noarch
perl-libs-4:5.24.1-383.fc25.i686
perl-libs-4:5.24.1-383.fc25.x86_64
python-cheetah-0:2.4.4-13.fc25.x86_64
python3-0:3.5.2-4.fc25.i686
python3-0:3.5.2-4.fc25.x86_64
python3-blessings-0:1.5-9.fc25.noarch
python3-bugzilla-0:1.2.2-4.fc25.noarch
python3-rpm-0:4.13.0-6.fc25.x86_64
python3-setuptools-0:25.1.1-1.fc25.noarch
rpm-build-0:4.13.0-6.fc25.x86_64
rpmdevtools-0:8.9-1.fc25.noarch
rpmlint-0:1.9-5.fc25.noarch
yum-utils-0:1.1.31-511.fc25.noarch
```

which erroneously lists `i686` packages besides the `x86_64` versions. Just passing `--arch x86_64` to the `dnf repoquery` command doesn't work. We would have to research how to fix it.

**Comment by dgoodwin** [comment]
Perhaps I should have linked this more clearly but what about "dnf builddep" which we already recommend the user run when a build fails due to missing dependencies. From the help it will "Install build dependencies for package or spec file".

**Comment by tjanez** [comment]
> Perhaps I should have linked this more clearly but what about "dnf builddep" which we already recommend the user run when a build fails due to missing dependencies.

Yes, we could also opt for the `dnf builddep` solution. It is quite heavy [1] but it will surely install everything a developer needs to run and *build* tito.

[1] On a freshly installed Fedora 25 Cloud Vagrant image, running `sudo dnf builddep tito.spec` in a fresh git clone of the tito repository produces:
```
Package git-2.9.3-2.fc25.x86_64 is already installed, skipping.
Package python3-setuptools-25.1.1-1.fc25.noarch is already installed, skipping.
Package python3-rpm-4.13.0-0.rc1.46.fc25.x86_64 is already installed, skipping.
Package tar-2:1.29-1.fc25.x86_64 is already installed, skipping.
Package which-2.21-1.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
============================================================================================================================================
 Package                                    Arch              Version                                              Repository          Size
============================================================================================================================================
Installing:
 aajohan-comfortaa-fonts                    noarch            2.004-6.fc24                                         fedora             151 k
 asciidoc                                   noarch            8.6.8-10.fc25                                        fedora             256 k
 atk                                        x86_64            2.22.0-1.fc25                                        fedora             263 k
 avahi-libs                                 x86_64            0.6.32-4.fc25                                        fedora              61 k
 binutils                                   x86_64            2.26.1-1.fc25                                        fedora             5.9 M
 boost-regex                                x86_64            1.60.0-10.fc25                                       updates            298 k
 cairo                                      x86_64            1.14.8-1.fc25                                        updates            720 k
 createrepo                                 noarch            0.10.3-10.fc25                                       fedora             100 k
 ctags                                      x86_64            5.8-18.fc24                                          fedora             167 k
 cups-libs                                  x86_64            1:2.2.0-5.fc25                                       updates            411 k
 docbook-dtds                               noarch            1.0-65.fc24                                          fedora             377 k
 docbook-style-xsl                          noarch            1.79.1-1.fc25                                        fedora             2.0 M
 dwz                                        x86_64            0.12-2.fc24                                          fedora             107 k
 elfutils                                   x86_64            0.167-2.fc25                                         fedora             298 k
 fakeroot                                   x86_64            1.20.2-4.fc24                                        fedora             101 k
 fakeroot-libs                              x86_64            1.20.2-4.fc24                                        fedora              35 k
 file                                       x86_64            5.28-4.fc25                                          fedora              69 k
 fontconfig                                 x86_64            2.12.1-1.fc25                                        fedora             244 k
 fontpackages-filesystem                    noarch            1.44-17.fc24                                         fedora              15 k
 fpc-srpm-macros                            noarch            1.0-1.fc25                                           fedora             7.6 k
 freetype                                   x86_64            2.6.5-1.fc25                                         fedora             358 k
 gd                                         x86_64            2.2.4-1.fc25                                         updates            136 k
 gdb-headless                               x86_64            7.12.1-41.fc25                                       updates            3.2 M
 gdk-pixbuf2                                x86_64            2.36.4-1.fc25                                        updates            455 k
 gdk-pixbuf2-modules                        x86_64            2.36.4-1.fc25                                        updates             96 k
 ghc-srpm-macros                            noarch            1.4.2-4.fc25                                         fedora             8.6 k
 ghostscript-core                           x86_64            9.20-6.fc25                                          updates            4.5 M
 ghostscript-fonts                          noarch            5.50-35.fc24                                         fedora             329 k
 gnat-srpm-macros                           noarch            4-1.fc25                                             fedora             9.0 k
 go-srpm-macros                             noarch            2-7.fc25                                             fedora             8.6 k
 graphite2                                  x86_64            1.3.6-1.fc25                                         fedora             115 k
 graphviz                                   x86_64            2.38.0-39.fc25                                       fedora             3.2 M
 gtk-update-icon-cache                      x86_64            3.22.7-1.fc25                                        updates             32 k
 gtk2                                       x86_64            2.24.31-2.fc25                                       fedora             3.4 M
 gts                                        x86_64            0.7.6-29.20121130.fc24                               fedora             226 k
 harfbuzz                                   x86_64            1.3.2-1.fc25                                         fedora             185 k
 hicolor-icon-theme                         noarch            0.15-3.fc24                                          fedora              46 k
 hwdata                                     noarch            0.296-1.fc25                                         updates            1.4 M
 jasper-libs                                x86_64            1.900.13-2.fc25                                      updates            153 k
 jbigkit-libs                               x86_64            2.1-5.fc24                                           fedora              52 k
 lasi                                       x86_64            1.1.2-6.fc24                                         fedora              46 k
 lcms2                                      x86_64            2.8-2.fc25                                           fedora             157 k
 libICE                                     x86_64            1.0.9-5.fc25                                         fedora              70 k
 libSM                                      x86_64            1.2.2-4.fc24                                         fedora              43 k
 libX11                                     x86_64            1.6.4-4.fc25                                         updates            614 k
 libX11-common                              noarch            1.6.4-4.fc25                                         updates            165 k
 libXau                                     x86_64            1.0.8-6.fc24                                         fedora              33 k
 libXaw                                     x86_64            1.0.13-4.fc25                                        fedora             190 k
 libXcomposite                              x86_64            0.4.4-8.fc24                                         fedora              27 k
 libXcursor                                 x86_64            1.1.14-6.fc24                                        fedora              34 k
 libXdamage                                 x86_64            1.1.4-8.fc24                                         fedora              25 k
 libXext                                    x86_64            1.3.3-4.fc24                                         fedora              41 k
 libXfixes                                  x86_64            5.0.3-1.fc25                                         fedora              22 k
 libXfont                                   x86_64            1.5.2-1.fc25                                         fedora             154 k
 libXft                                     x86_64            2.3.2-4.fc24                                         fedora              62 k
 libXi                                      x86_64            1.7.9-1.fc25                                         updates             44 k
 libXinerama                                x86_64            1.1.3-6.fc24                                         fedora              18 k
 libXmu                                     x86_64            1.1.2-4.fc24                                         fedora              74 k
 libXpm                                     x86_64            3.5.12-1.fc25                                        updates             54 k
 libXrandr                                  x86_64            1.5.1-1.fc25                                         fedora              29 k
 libXrender                                 x86_64            0.9.10-1.fc25                                        fedora              29 k
 libXt                                      x86_64            1.1.5-3.fc24                                         fedora             178 k
 libXxf86vm                                 x86_64            1.1.4-3.fc24                                         fedora              22 k
 libbabeltrace                              x86_64            1.4.0-3.fc25                                         fedora             164 k
 libcroco                                   x86_64            0.6.11-2.fc24                                        fedora             108 k
 libdatrie                                  x86_64            0.2.9-3.fc25                                         fedora              31 k
 libdrm                                     x86_64            2.4.75-1.fc25                                        updates            153 k
 libfontenc                                 x86_64            1.1.3-3.fc24                                         fedora              35 k
 libicu                                     x86_64            57.1-4.fc25                                          updates            8.4 M
 libipt                                     x86_64            1.5-1.fc25                                           fedora              38 k
 libjpeg-turbo                              x86_64            1.5.1-0.fc25                                         fedora             153 k
 libpciaccess                               x86_64            0.13.4-3.fc24                                        fedora              30 k
 libpng                                     x86_64            2:1.6.27-1.fc25                                      updates            120 k
 librsvg2                                   x86_64            2.40.16-2.fc25                                       fedora             133 k
 libthai                                    x86_64            0.1.25-1.fc25                                        fedora             197 k
 libtiff                                    x86_64            4.0.7-2.fc25                                         updates            175 k
 libwayland-client                          x86_64            1.12.0-1.fc25                                        fedora              35 k
 libwayland-server                          x86_64            1.12.0-1.fc25                                        fedora              40 k
 libwebp                                    x86_64            0.5.2-1.fc25                                         updates            244 k
 libxcb                                     x86_64            1.12-1.fc25                                          fedora             208 k
 libxshmfence                               x86_64            1.2-3.fc24                                           fedora              11 k
 libxslt                                    x86_64            1.1.28-13.fc25                                       fedora             247 k
 mesa-libEGL                                x86_64            13.0.3-5.fc25                                        updates            101 k
 mesa-libGL                                 x86_64            13.0.3-5.fc25                                        updates            163 k
 mesa-libgbm                                x86_64            13.0.3-5.fc25                                        updates             42 k
 mesa-libglapi                              x86_64            13.0.3-5.fc25                                        updates             49 k
 netpbm                                     x86_64            10.76.00-2.fc25                                      updates            192 k
 ocaml-srpm-macros                          noarch            2-4.fc24                                             fedora             8.0 k
 openjpeg2                                  x86_64            2.1.2-3.fc25                                         updates            115 k
 pango                                      x86_64            1.40.3-1.fc25                                        fedora             280 k
 patch                                      x86_64            2.7.5-3.fc24                                         fedora             125 k
 perl-srpm-macros                           noarch            1-20.fc25                                            fedora              10 k
 pixman                                     x86_64            0.34.0-2.fc24                                        fedora             259 k
 poppler-data                               noarch            0.4.7-6.fc25                                         updates            2.2 M
 pyliblzma                                  x86_64            0.5.3-16.fc25                                        fedora              54 k
 python                                     x86_64            2.7.13-1.fc25                                        updates             96 k
 python-bugzilla                            noarch            1.2.2-4.fc25                                         fedora              94 k
 python-chardet                             noarch            2.3.0-1.fc25                                         fedora             233 k
 python-libs                                x86_64            2.7.13-1.fc25                                        updates            5.8 M
 python-libxml2                             x86_64            2.9.3-4.fc25                                         fedora             226 k
 python-magic                               noarch            5.28-4.fc25                                          fedora              40 k
 python-pip                                 noarch            8.1.2-2.fc25                                         fedora             1.7 M
 python-pycurl                              x86_64            7.43.0-4.fc25                                        fedora             242 k
 python-rpm-macros                          noarch            3-10.fc25                                            fedora             9.1 k
 python-six                                 noarch            1.10.0-3.fc25                                        fedora              35 k
 python-srpm-macros                         noarch            3-10.fc25                                            fedora             8.4 k
 python-urlgrabber                          noarch            3.10.1-9.fc25                                        fedora             112 k
 python2-deltarpm                           x86_64            3.6-17.fc25                                          fedora              36 k
 python2-iniparse                           noarch            0.4-20.fc25                                          fedora              46 k
 python2-pygpgme                            x86_64            0.3-18.fc25                                          fedora              90 k
 python2-pysocks                            noarch            1.5.6-5.fc25                                         fedora              25 k
 python2-requests                           noarch            2.10.0-4.fc25                                        fedora             107 k
 python2-rpm                                x86_64            4.13.0-6.fc25                                        updates            105 k
 python2-setuptools                         noarch            25.1.1-1.fc25                                        fedora             506 k
 python2-urllib3                            noarch            1.15.1-3.fc25                                        fedora             128 k
 python3-bugzilla                           noarch            1.2.2-4.fc25                                         fedora              78 k
 python3-devel                              x86_64            3.5.2-4.fc25                                         fedora             204 k
 python3-magic                              noarch            5.28-4.fc25                                          fedora              41 k
 python3-rpm-macros                         noarch            3-10.fc25                                            fedora             8.5 k
 pyxattr                                    x86_64            0.5.3-8.fc25                                         fedora              34 k
 qt5-srpm-macros                            noarch            5.7.1-1.fc25                                         updates            7.9 k
 redhat-rpm-config                          noarch            45-1.fc25                                            updates             60 k
 rpm-build                                  x86_64            4.13.0-6.fc25                                        updates            147 k
 rpmdevtools                                noarch            8.9-1.fc25                                           fedora             105 k
 sgml-common                                noarch            0.6.3-44.fc24                                        fedora              59 k
 source-highlight                           x86_64            3.1.8-8.fc25                                         fedora             647 k
 unzip                                      x86_64            6.0-31.fc25                                          updates            184 k
 urw-fonts                                  noarch            3:2.4-22.fc24                                        fedora             3.0 M
 vim-filesystem                             x86_64            2:8.0.238-1.fc25                                     updates             31 k
 xemacs-filesystem                          noarch            21.5.34-20.20170124hgf412e9f093d4.fc25               updates             21 k
 xml-common                                 noarch            0.6.3-44.fc24                                        fedora              31 k
 xorg-x11-font-utils                        x86_64            1:7.5-32.fc25                                        fedora              81 k
 xorg-x11-fonts-ISO8859-1-100dpi            noarch            7.5-16.fc24                                          fedora             1.1 M
 yum                                        noarch            3.4.3-510.fc25                                       fedora             1.2 M
 yum-metadata-parser                        x86_64            1.1.4-17.fc25                                        fedora              39 k
 zip                                        x86_64            3.0-16.fc24                                          fedora             272 k
Upgrading:
 python3-rpm                                x86_64            4.13.0-6.fc25                                        updates            105 k
 rpm                                        x86_64            4.13.0-6.fc25                                        updates            517 k
 rpm-build-libs                             x86_64            4.13.0-6.fc25                                        updates            121 k
 rpm-libs                                   x86_64            4.13.0-6.fc25                                        updates            303 k
 rpm-plugin-selinux                         x86_64            4.13.0-6.fc25                                        updates             56 k
 rpm-plugin-systemd-inhibit                 x86_64            4.13.0-6.fc25                                        updates             56 k
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 tar                                        x86_64            2:1.29-3.fc25                                        updates            813 k

Transaction Summary
============================================================================================================================================
Install  136 Packages
Upgrade    6 Packages
Skip       1 Package

Total download size: 64 M
Is this ok [y/N]:
```

**Comment by FrostyX** [comment]
Hello @tjanez,
thank you for the contribution, I am sorry it hung here so long without merging.

What should we do now? I am not sure. There is a merge conflict in `tito.spec` that will need to be resolved.

When I tried to follow your `virtualenv` instructions and then did

    (tito-venv) [jkadlcik@localhost tito]$ tito-venv/bin/tito --build --srpm

I got the help screen, it seems like parameters weren't properly passed

    Usage: tito MODULENAME --help
    Supported modules:
       build    - Build packages.
       init     - Initialize directory for use by tito.
       ...

Personally, I don't use `virtualenv`, so it is possible that it is a PEBKAC. Either way, it would be nice to show how to execute tito properly, after installing it with `pip`.

Also, I don't want the pip installation to be the only way to run tito locally from sources, so I would like to have \_\_main\_\_ somewhere (probably in `src/tito/cli.py`).

    if __name__ == "__main__":
        main()

Besides this, I see no problem with merging.

What are your thoughts about this?

**Comment by FrostyX** [comment]
ping @tjanez

**Comment by FrostyX** [comment]
gently pinging again @tjanez

**Comment by tjanez** [comment]
> Hello @tjanez,
> thank you for the contribution, I am sorry it hung here so long without merging.

Yea, it's been a while.

> What should we do now? I am not sure. There is a merge conflict in `tito.spec` that will need to be resolved.

Done.

> When I tried to follow your `virtualenv` instructions and then did
> 
> ```
> (tito-venv) [jkadlcik@localhost tito]$ tito-venv/bin/tito --build --srpm
> ```
> 
> I got the help screen, it seems like parameters weren't properly passed
> 
> ```
> Usage: tito MODULENAME --help
> Supported modules:
>    build    - Build packages.
>    init     - Initialize directory for use by tito.
>    ...
> ```

Hmm... I think you should use `tito build --srpm` instead of `tito --build --srpm`:

```
(tito-venv) [root@ca5f19f9c83c tito]# which tito
/tito/tito-venv/bin/tito
(tito-venv) [root@ca5f19f9c83c tito]# tito build --help
Usage: tito build [options]

Options:
  -h, --help            show this help message and exit
  --debug               print debug messages
  --offline             do not attempt any remote communication (avoid using
                        this please)
  -o OUTPUTDIR, --output=OUTPUTDIR
                        Path to write temp files, tarballs and rpms to.
                        (default /tmp/tito)
  --tgz                 Build .tar.gz
  --srpm                Build srpm
  --rpm                 Build rpm
  -i, --install         Install any binary rpms being built. (WARNING: uses
                        sudo rpm -Uvh --force)
  --no-sudo             Don't escalate privileges when installing. Use when
                        running this command with required privileges.
  --dist=DISTTAG        Dist tag to apply to srpm and/or rpm. (i.e. .el5)
  --test                use current branch HEAD instead of latest package tag
  --no-cleanup          do not clean up temporary tito build
                        directories/files, and disable rpmbuild %clean
  --tag=PKGTAG          build a specific tag instead of the latest version
                        (i.e. spacewalk-java-0.4.0-1)
  --builder=BUILDER     Override the normal builder by specifying a full class
                        path or one of the pre-configured shortcuts.
  --arg=BUILDER_ARGS    Custom arguments specific to a particular builder.
                        (key=value)
  --quiet               Suppress output from the build process.
  --verbose             Expose more output from the build process.
  --rpmbuild-options=OPTIONS
                        Options to pass to rpmbuild.
  --scl=COLLECTION      Build package for software collection.
```
 
> Also, I don't want the pip installation to be the only way to run tito locally from sources, so I would like to have __main__ somewhere (probably in `src/tito/cli.py`).
> 
> ```
> if __name__ == "__main__":
>     main()
> ```

Good idea, I've added it.

> Besides this, I see no problem with merging.
> 
> What are your thoughts about this?

I've also updated source installation instructions in the README which are then referenced in HACKING.

Please, take a look.

**Comment by FrostyX** [comment]
Thank you for going back to the past with me :D

> Hmm... I think you should use tito build --srpm instead of tito --build --srpm

Oh god, what an embarrassing typo. You are right of course.

> Please, take a look.

I am going to look at this ASAP.

**Comment by FrostyX** [comment]
Except for that failed Travis, it looks good to me.

**Comment by tjanez** [comment]
> The Travis CLI fails because of
> 
> ```
> /home/sandbox/test/unit/../../src/tito/cli.py:899:1:
> E305 expected 2 blank lines after class or function definition, found 1
> ``` 
> can you please look at that?

I've fixed that.

Travis now fails with the same results as [on the `master` branch (build #187)](https://travis-ci.org/github/dgoodwin/tito/builds/660253916?utm_medium=notification&utm_source=github_status):
```
=====================
Summary
/tmp/centos-6-python.out                : OK
/tmp/centos-7-python.out                : OK
/tmp/fedora-27-python.out               : OK
/tmp/fedora-27-python3.out              : OK
/tmp/fedora-rawhide-python3.out         : FAILED (SKIP=2, errors=15)
The command "hacking/runtests.sh" exited with 1.
```

So I think this is not a regression of this pull request.

**Comment by FrostyX** [comment]
> Travis now fails with the same results as on the master branch (build #187):
> So I think this is not a regression of this pull request.

Yea, I am trying to figure that one out

Thank you for the changes, I am glad that we were able to finish this PR, even though it was after a long time.

**Comment by tjanez** [comment]
> > Travis now fails with the same results as on the master branch (build #187):
> > So I think this is not a regression of this pull request.
> 
> Yea, I am trying to figure that one out

:+1: 

> Thank you for the changes, I am glad that we were able to finish this PR, even though it was after a long time.

No problem. Thank you for picking it up!

**Pull request merged**
