### PR TITLE
Only pass one project_name to copr build command

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by dgoodwin** [comment]
What's the situation where a releaser config would have multiple copr project names? Is that bad config or somehow valid?

**Comment by domcleal** [comment]
It's a valid config, but wasn't working correctly.  The releasers.conf man page suggests it should work in the same way as the KojiReleaser's autobuild_tags, which accepts multiple tag names.

The releaser already tries to handle multiple project names in places (e.g. https://github.com/dgoodwin/tito/blob/tito-0.6.6-1/src/tito/release/copr.py#L49-L52), but when used it was passing all project names into every `copr build` call:

<pre>
WARNING: Skipping command due to --dry-run: /usr/bin/copr-cli build --nowait @theforeman/foreman-nightly-nonscl-rhel6 @theforeman/foreman-nightly-nonscl-rhel7 @theforeman/foreman-nightly-scl-rhel6 @theforeman/foreman-nightly-scl-rhel7 /tmp/tito/tfm-rubygem-fog-xml-0.1.2-4.el6.src.rpm
Wrote: /tmp/tito/tfm-rubygem-fog-xml-0.1.2-4.el7.src.rpm


WARNING: Skipping command due to --dry-run: /usr/bin/copr-cli build --nowait @theforeman/foreman-nightly-nonscl-rhel6 @theforeman/foreman-nightly-nonscl-rhel7 @theforeman/foreman-nightly-scl-rhel6 @theforeman/foreman-nightly-scl-rhel7 /tmp/tito/tfm-rubygem-fog-xml-0.1.2-4.el7.src.rpm
</pre>

**Comment by dgoodwin** [comment]
Awesome, thank you.

**Comment by xsuchy** [comment]
I do not get it. Previously it pass to copr-cli as project name the value from releasers.conf the value of. E.g. I have in releasers.conf:
```
[@copr]
releaser = tito.release.CoprReleaser
project_name = @copr/copr

[@copr-dev]
releaser = tito.release.CoprReleaser
project_name = @copr/copr-dev
builder.test = 1
```
Now you pass tag as project name? it does not have sense.

**Comment by xsuchy** [comment]
Ah, I get it now. It took me some time.

**Comment by domcleal** [comment]
Sorry, clearly I didn't indicate the problem well!  For the record, it's when you have `project_name` set to multiple projects, e.g. `project_name = @copr/copr @copr/copr-dev`. If it's to work like Koji's autobuild_tags, then it should submit the build to each project name ("tag") in turn.

Thanks all.

**Pull request merged**
