### PR TITLE
add support for %autosetup

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Reference: https://github.com/dgoodwin/tito/issues/218
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@dgoodwin this is what I tried to say in issue. I didn't tested this patch, but if it will not work you will know what I meant

**Comment by ignatenkobrain** [comment]
in simple case with `%autosetup` this patch works. I didn't tested it with `%patch` case, because I don't know how to reproduce it

**Comment by dgoodwin** [comment]
Thanks it does not quite work, I had one in progress from yesterday quite similar that was also failing the same way, I will get them combined somehow and should have it working soon.

**Comment by ignatenkobrain** [comment]
hm, can you show me what's the problem with my patch?

**Comment by dgoodwin** [comment]
It looks like with %autosetup, if you build with --test and --no-cleanup, the resulting spec comes out with something like %autosetup -n tito-%{version} -n tito-correctversion, the build actually works but it's not correctly taking out the pre-existing -n. 

And with %setup as is the test spec file seemed to come out with a trailing -p1. I'm not quite sure why that happened yet.

**Comment by ignatenkobrain** [comment]
@dgoodwin problem with appending `-p1` fixed by https://github.com/dgoodwin/tito/pull/219/commits/d802362964ae28f2610a3c952ba4a006bb26496f

**Comment by ignatenkobrain** [comment]
@dgoodwin just tested tito from my branch:

After `tito build --test --srpm --no-cleanup` I see that bug, I guess it's only one remaining bug here

**Comment by dgoodwin** [comment]
Yeah just that one remaining issue but at least the autosetup build will pass. 

%autosetup -n tito-%{version} -n tito-git-3.20362dd -p1

**Comment by dgoodwin** [comment]
I should get back to my regular workload but I will take a look at that last issue hopefully before long unless you get it figured out first. It might be nice to extract the setup macro processing into another little function we could unit test in test/unit/ very quickly.

**Comment by dgoodwin** [comment]
Your commits have been manually merged, I added some tests and a fix for the regex.

Thanks for the contribution!

**Comment by ignatenkobrain** [comment]
@dgoodwin thanks! Can you apply this patches to F23+?

**Comment by dgoodwin** [comment]
Builds submitted and in need of karma: https://bodhi.fedoraproject.org/users/dgoodwin

**Pull request closed without merging**
